Feature sn 44 colors in the main interface
infoshareacademy/jpydzr2-snaver pull request #37
Opened 2021-03-31 06:12 UTC by robrach

2021-04-03 10:14 UTC, antymoro requested changes
Zostawiłem w komentarzu uwagi. Robert, daj proszę znać, jaki masz do nich stosunek :)

2021-04-03 10:14 UTC, antymoro commented on controllers/budget_controller.py
>              activity_amount = sum(activity.amount_outflow for activity in category.transactions)
Myślę, że tutaj lepiej byłoby dodać kwerkę aniżeli pętlę

2021-04-03 10:14 UTC, antymoro commented on controllers/budget_controller.py
> +            bar = f"\033[{i_color}m{int(activity_amount//100)*'█'}{bar_ending}{style.RESET}"
Moim zdaniem to się powinno proporcjonalnie wyliczać, a nie tak jak obecnie - floor division.

Lepiej byłoby, gdyby kategoria z największymi wydatkami to byłoby 100 "barów". Pozostałe proporcjonalnie mniej.

2021-04-03 10:14 UTC, antymoro commented on controllers/budget_controller.py
>      for parent in budget.parent_categories:
Zadanie z gwiazdką - czy można to zaimplementować bez pętli?

2021-04-03 10:14 UTC, antymoro commented on models/Category.py
> +        if self.available_amount == 0:
Myślę, że można to zrefaktorować - zapisać "style" do zmiennej i umieścić go w if-ach, a nie "availabe_amount" jak obecnie.

2021-04-03 10:14 UTC, antymoro commented on models/ParentCategory.py
> +            category = f"{style.tBLUE}[{self.id}] {self.name.upper()}{style.RESET}"
Tutaj tak samo - myślę, że zmienna "style" powinna być w if-ach, nie sum_amount.

2021-04-06 15:02 UTC, robrach commented
Wstrzymuję się z tym pullrequestem do momentu zakończenia prac nad SN-41-months.

2021-04-06 15:02 UTC, closed without merging